// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyxaZUtKiFLPOIz9JnS_3tjXfQbg-znPE',
    appId: '1:932968375077:web:92b42d374a8b690f12b0cc',
    messagingSenderId: '932968375077',
    projectId: 'eventplannerapp-5396c',
    authDomain: 'eventplannerapp-5396c.firebaseapp.com',
    storageBucket: 'eventplannerapp-5396c.firebasestorage.app',
    measurementId: 'G-YJG8YZR80M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKc_t3CGliDKtnCbPnjFSXS_b0z11LaY',
    appId: '1:932968375077:android:55bd31b48f8d205612b0cc',
    messagingSenderId: '932968375077',
    projectId: 'eventplannerapp-5396c',
    storageBucket: 'eventplannerapp-5396c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAwqkZ5BpISx9pDZrHALnbVZmNTeIgum0',
    appId: '1:932968375077:ios:313d7900127b354112b0cc',
    messagingSenderId: '932968375077',
    projectId: 'eventplannerapp-5396c',
    storageBucket: 'eventplannerapp-5396c.firebasestorage.app',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAwqkZ5BpISx9pDZrHALnbVZmNTeIgum0',
    appId: '1:932968375077:ios:313d7900127b354112b0cc',
    messagingSenderId: '932968375077',
    projectId: 'eventplannerapp-5396c',
    storageBucket: 'eventplannerapp-5396c.firebasestorage.app',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyxaZUtKiFLPOIz9JnS_3tjXfQbg-znPE',
    appId: '1:932968375077:web:90d434d0cd3e9e5c12b0cc',
    messagingSenderId: '932968375077',
    projectId: 'eventplannerapp-5396c',
    authDomain: 'eventplannerapp-5396c.firebaseapp.com',
    storageBucket: 'eventplannerapp-5396c.firebasestorage.app',
    measurementId: 'G-8KE5EFL3ZX',
  );
}
